### ISSUE TITLE
MySQL 5.7 modes for blank string ids and dates

### ISSUE THREAD

**Issue by ThriceGood** [openillink-project/openillink#14]
Hello,

I have been trying to set up OpenILLink with MySQL 5.7 and I was having issues creating orders because of inserting blank strings for 'illinkid' and when various date fields are not filled in. To fix this I removed the MySQL modes STRICT_TRANS_TABLES, NO_ZERO_IN_DATE and NO_ZERO_DATE from the default MySQL modes in 5.7 and I was getting no issues.

Programatically it can be fixed by removing 'illinkid' from the 'orders_new' INSERT query and letting auto-increment handle it, and setting empty dates to Null instead of '0000-00-00'. Would there be a reason for not doing this?

**Comment by jeromecaffaro** [comment]
Thank you for the report. The issue has been resolved as part of commit 268993e and commit 38755a3
